In [4]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist, cifar10
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt 
import numpy as np
import seaborn as sns
from sklearn.metrics import confusion_matrix  
import pathlib
import PIL
import cv2

from tensorflow.keras import models, layers 

[[[ 46  88  81]
  [  0   9   6]
  [  0   7   4]
  ...
  [ 58 101  80]
  [ 78 124 105]
  [ 45  78  63]]

 [[ 83 113 108]
  [  0   3   0]
  [ 15  18  16]
  ...
  [ 17  31  19]
  [127 143 132]
  [ 43  46  37]]

 [[ 32  46  42]
  [ 13  14  12]
  [ 22  21  17]
  ...
  [ 14  30  19]
  [ 98 115 106]
  [ 48  51  42]]

 ...

 [[ 61  66  65]
  [ 53  55  56]
  [ 70  69  73]
  ...
  [ 87  80  65]
  [131 122 112]
  [102  93  84]]

 [[ 75  87  87]
  [ 51  56  57]
  [180 179 181]
  ...
  [ 62  55  62]
  [116 108 119]
  [ 58  48  65]]

 [[114 131 134]
  [ 98 108 108]
  [160 161 159]
  ...
  [ 80  75  74]
  [ 62  55  60]
  [ 49  40  50]]]
